### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by zeinaeddo** [herlesupreeth/docker_open5gs#106]
Hello,

I can see that IPv6 is not supported in this implementation. Do you mean IPv6 signaling support or IPv6 UE allocation? Why isn't supported? And is there any plan on the roadmap to support it as well ad dual-stack?

Regards,
Zeina

**Comment by herlesupreeth** [comment]
IPv6 is supported both at UE allocation and signalling sense from the perspective of open5gs however its slightly headache to support in docker-compose and also I am not sure whether IMS works with IPv6 without crashing or not

**Comment by herlesupreeth** [comment]
Unfortunately I don't think to work on IMS IPv6 support hence I don't plan to add IPv6 support.

**Comment by herlesupreeth** [comment]
Its lot of work supporting/fixing issue related to IPv6 usage in IMS so not adding support in docker-compose anytime soon so closing this for now.

**Comment by nishant412** [comment]
@herlesupreeth Just wanted to check if ipv6 is still not supported? I like to try and contribute to get ipv6 working here, so it will be great if you can give an overview of where you are at/changes you believe we need to do/problems that you are facing

**Comment by herlesupreeth** [comment]
Hey @nishant412 , the state of IPv6 support is more or less the same as I mentioned above on Aug 2022. The easiest part here is the enabling of IPv6 in docker and let open5gs assign IPv6 as open5gs has full support for IPv6. I didnt work on IPv6 at all because I am not sure kamailio IMS is bug-proof when using IPv6. My idea initially was to test kamailio IMS with standalone core + IMS (non-dockerized) using IPv6 and only when I am sure it works without manjor bugs, I would port it to this repo. But I never managed get around this task. Since this repo helps people deploy Core Network + IMS in a easy manner I didnt want to introduce IPv6 right away without proper testing.

**Comment by herlesupreeth** [comment]
> So if I understand correctly, from looking at the configs, if I were to go to 4g-volte-deploy.yaml and add subnet 2001:230::/64 to networks->default->ipam->config , and then add an ipv6_address to networks->default on each of the core components, and then enable ipv6 forwarding, that should atleast turn on ipv6 addreses on open5gs, and therefore my UEs will get an ipv6 address on the internet APN.

That is correct. Sorry for the late reply

**Comment by gustavobsch** [comment]
@nishant412 did you get IPv6 working? I'm looking into this as well
