### ISSUE TITLE
 Can't make another call after making the 5th call

### ISSUE THREAD

**Issue by alf-askey** [herlesupreeth/docker_open5gs#20]
precodidtion
1) phone_1 config "automatical answer"
2) phone_1/2 power off

test steps
1) power on phone_1/2 
2) phone_1/2 attach and resister to open5gs with IMS
3) phone_2(tel:0713) call phone_1(tel:0711) base on mo_mt.bat script as the below
        @echo off
	:loop
	d:\tools\adb\adb -s a624bfc3 shell am start -a android.intent.action.CALL -d tel:0711
	timeout /t 60
	d:\tools\adb\adb -s a624bfc3 shell input keyevent KEYCODE_ENDCALL
	timeout /t 10
	goto loop

result:
step 3) after 5th loop , phone_2 call phone_1 fail , packet as the attached files

[make call fail after making the 5th call.zip](https://github.com/herlesupreeth/docker_open5gs/files/5884422/make.call.fail.after.making.the.5th.call.zip)
[syslog.zip](https://github.com/herlesupreeth/docker_open5gs/files/5884473/syslog.zip)

**Comment by herlesupreeth** [comment]
Wow!!! you are doing an awesome work at automating this testing. Nice work

Regarding the failed calls, its because of below error
![image](https://user-images.githubusercontent.com/4115839/106098481-64f8f700-6139-11eb-8e42-4912218dc2c1.png)

As you can see the E-RAB setup is failing resulting in Pre-Condition failure for the call. This is definitely a issue arising either from eNB or open5gs so I would suggest to do the following,

1. Update the open5gs base docker image to point to latest release tag (https://github.com/herlesupreeth/docker_open5gs/blob/master/base/Dockerfile)
 
In this above file change `git checkout tags/v2.0.20` to point to latest release 

2. Re-compile only the open5gs components and give it a try
3. If the problem still persists better to open an issue on open5gs repo

**Comment by alf-askey** [comment]
Thank your help, you help me very much , it is "eNB" issue . 
I change it to amarisoft 's eNB ,it is pass on mo/mt calling over 20 loop

**Comment by herlesupreeth** [comment]
Slightly off-topic: If i may ask, can you tell me how much you paid for Amarisoft eNB License? I am interested in buying one

**Comment by alf-askey** [comment]
we buy machine(PC+6 SDR card) with Amarisoft eNB License ,it about 75000 euro
We bought it from an agent in Taiwan , you can contact sales@amarisoft.com
