### ISSUE TITLE
SMS is not working in Samsung mobile.

### ISSUE THREAD

**Issue by shanmukhapothana** [herlesupreeth/docker_open5gs#211]
Hi Team,
i am using open5gs_hss_cx (commit f0ead8c5b140381f3ea37645421d51f6ed066f9b) branch to test volte and sms.
Lte is attached successfully and we are able establish the call .
We are able to send the sms from  one plus mobile to samsung mobile but while trying to send sms from samsung to oneplus mobile its getting failed.

kindly find the attached log.
[smsc.log](https://github.com/herlesupreeth/docker_open5gs/files/12357871/smsc.log)

**Comment by herlesupreeth** [comment]
Please send a pcap for the issue. Logs are good but not enough to analyze the issue.

**Comment by shanmukhapothana** [comment]
please kindly attached the logs of pcap[https://res.cdn.office.net/assets/mail/file-icon/png/generic_16x16.png]sms_failed_samsung.pcapng<https://mobiveilchn-my.sharepoint.com/:u:/g/personal/p_shanmukha_mobiveil_co_in/EZI0fK8Vcq9HlyF2Bw1_gCcBf8NFILcY-URNStConryH8Q>
________________________________

**Comment by herlesupreeth** [comment]
Link is broken. Please re-check your link

**Comment by shanmukhapothana** [comment]
Hi @herlesupreeth  after rerun the core network  i am able to send few text messages from samsung mobile to one plus 

but after trying to send emoji's,sms is getting failed after i am not able to send any text messages also .


[sms.zip](https://github.com/herlesupreeth/docker_open5gs/files/12358203/sms.zip)

**Comment by herlesupreeth** [comment]
I am not sure whether kamailio based SMSC supports emoji (since its just a Proof-Of-Concept system not a telco grade SMSC) or not but I can see whether it can be fixed or not. For the I need the logs and pcap for the following scenario. Thanks

1. Stop all components
2. Start tcpdump/wireshark
3. Bring up the components
4. Start eNB and attach UE
5. Send SMS with emoji
6. Wait for it to fail and stop the trace
7. Send me the logs on SMSC and pcap captured

**Comment by herlesupreeth** [comment]
@shanmukhapothana I have fixed the SMSC code. You need to fetch the latest commits and re-compile docker_kamailio image and then give a try. Emoji should work now

**Comment by shanmukhapothana** [comment]
hi @herlesupreeth thankyou ,now i am able to send  Emoji  but in oneplus UE i am not able to attach LTE network suppose i turn ON the apn enable option in APN setting

[internet_fail.zip](https://github.com/herlesupreeth/docker_open5gs/files/12407419/internet_fail.zip)


suppose i disable APN option in APN setting i am able to attach the network and volte is working but i am not getting internet .

**Comment by herlesupreeth** [comment]
You should not have "IMS" APN selected in APN settings. "internet" APN should be selected

**Comment by shanmukhapothana** [comment]
hi @herlesupreeth as we already configured "internet" apn and "ims" apn and we select the apn as "internet" only, still we are facing the same issue.
[Apn.zip](https://github.com/herlesupreeth/docker_open5gs/files/12407643/Apn.zip)
 kindly find the above attached image apn's.

**Comment by herlesupreeth** [comment]
Then I would suggest to reset APN settings to default. Then,

1. Create internet APN
2. Create ims APN
3. And from list of APNs select only (Radio button) internet APN
4. Then attach the phone and give it a try

If it still fails then I cant help since it a setting on the phone OS and cant be changed without rooting the phone

**Comment by shanmukhapothana** [comment]
okay.Thank you
