### ISSUE TITLE
why there are no nr-ue and nr-gnb?

### ISSUE THREAD

**Issue by horser1** [herlesupreeth/docker_open5gs#30]
@miaoski @herlesupreeth hello!  in ueransim program, there is nr-ue and nr-gnb in ./UERANSIM/build
![图片](https://user-images.githubusercontent.com/48501653/113411495-7f28ad00-93e8-11eb-961f-43ae0c5a9538.png)
but in the container of UERANSIM, there are no nr-ue or nr-gnb. 
I want to know that when I start the container UERANSIM, did the ue or ran start? 
or how to did this operation(nr-ue -c myconfig1.yaml    nr-gnb -c myconfig2.yaml) like ueransim program in container?
thanks!!!

**Comment by herlesupreeth** [comment]
@horser1 The docker file in this repo as still using an old version of UERANSIM, I havent had time to update it yet. Once I do it I will update you

**Comment by horser1** [comment]
@herlesupreeth when the ueransim container start, I attach the amf container, but I see nothing in amf container. 
I think there should be some information? like:
![图片](https://user-images.githubusercontent.com/48501653/113720536-545c9280-9721-11eb-85cb-02865569eb84.png)

**Comment by herlesupreeth** [comment]
@horser1 Now UERANSIM has also been bumped to latest code and you have nr-gnb and nr-ue. Since the open5gs has also been bumped to latest code which involves new DB schema. I would suggest to drop the docker volume docker_open5gs_mongodbdata as follows

`docker volume rm docker_open5gs_mongodbdata`

and then re-compile open5gs base image and re-compile all the CN components and give it try (dont forget to re-add the SIM details via open5gs Web UI)
