### ISSUE TITLE
MME not responding to Create Bearer Request after device wake up

### ISSUE THREAD

**Issue by NUCLEAR-WAR** [herlesupreeth/docker_open5gs#306]
Hi,

I have an issue when the device wake up and make a call, the MME is not responding to Create Bearer Request, this lead the call to eventually dropped 
Could you please check what could be wrong ?

[voicemail_fail.zip](https://github.com/herlesupreeth/docker_open5gs/files/14910644/voicemail_fail.zip)
[upf.log](https://github.com/herlesupreeth/docker_open5gs/files/14910645/upf.log)
[smf.log](https://github.com/herlesupreeth/docker_open5gs/files/14910647/smf.log)
[sgwu.log](https://github.com/herlesupreeth/docker_open5gs/files/14910648/sgwu.log)
[sgwc.log](https://github.com/herlesupreeth/docker_open5gs/files/14910649/sgwc.log)
[pcrf.log](https://github.com/herlesupreeth/docker_open5gs/files/14910651/pcrf.log)
[mme.log](https://github.com/herlesupreeth/docker_open5gs/files/14910652/mme.log)

Best Regards

**Comment by herlesupreeth** [comment]
![image](https://github.com/herlesupreeth/docker_open5gs/assets/4115839/881037c3-be85-4ffb-9497-97b2c49a9c39)

Looks like your UE lost connection with eNB right after dedicated bearer setup request is sent. Cant figure out much from the logs why UE is losing connection to eNB since there is lot going on. Maybe if you could repeat with clean setup I can take a look. i.e. stop all components (Core Network + eNB), attach UEs, let UEs go to sleep, wake up and then make a call. Send me logs and pcap of this scenario

**Comment by herlesupreeth** [comment]
> I will recreate the Environment on new Hardware, also I am planning to add REF Link to my b200mini, maybe there is some frequency drifting, do you know if Leo Bodnar GPSDO works with the mini version of this USRP ?

yes, it should work as there is reference input of 10Mhz

> Also, what hardware specs do you recommend to run the eNB and gNB on it, I am planing also to buy new PC to run those on it.

If you are buying a USRP B200mini, then maximum BW you can test is around 50Mhz. And, in order to run a gNB/eNB with 50Mhz BW you dont need very powerful machine. You can easily run on a ultra thin laptop for example, the one with below AMD CPU I can easily run 50Mhz without any lates

```
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         48 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  16
  On-line CPU(s) list:   0-15
Vendor ID:               AuthenticAMD
  Model name:            AMD Ryzen 7 5825U with Radeon Graphics
```

**Comment by herlesupreeth** [comment]
I recently pushed a fix to kamailio source code so can you please pull latest changes in this repo and re-build kamailio image and give it a try?

**Comment by NUCLEAR-WAR** [comment]
is it the one from three weeks ago ?

**Comment by herlesupreeth** [comment]
yes

**Comment by NUCLEAR-WAR** [comment]
Hi @herlesupreeth,

with the new update, now Kamailio responded to the Device, so now everything is working as expected, the device is recovering the Radio/Bearer and SIP after idle, I also increased the SIP OPTIONS Interval to let the device goes to idle mode ( power save), the device will recover if the a SIP OPTIONS received.

I attached the traces for three use cases where the device recovers from Idle Mode, just if you are interested.
[afterfix_newTest_UE-SR_with_mac-lte-f.zip](https://github.com/user-attachments/files/15977187/afterfix_newTest_UE-SR_with_mac-lte-f.zip)
[afterfix_newTest_Network-SR-with_mac-lte-f.zip](https://github.com/user-attachments/files/15977189/afterfix_newTest_Network-SR-with_mac-lte-f.zip)
[afterfix_MO_MT_IDLE_with_mac-lte_f.zip](https://github.com/user-attachments/files/15977192/afterfix_MO_MT_IDLE_with_mac-lte_f.zip)


Many thanks for your wonderful help!

Best Regards

**Comment by herlesupreeth** [comment]
Thats great to hear. Glad to be of help!!
