### ISSUE TITLE
About NAT issue between PCSCF and UPF/PGW-U

### ISSUE THREAD

**Issue by bluehat-f** [herlesupreeth/docker_open5gs#36]
First of all, thanks for the great project.
According to doc in https://open5gs.org/open5gs/docs/tutorial/03-VoLTE-dockerized. It's clear that UPF/PGW-U and PCSCF can't support NAT. Is possible for PCSCF to support IPSEC ESP NAT? Does kamailio support ipsec NAT? Sometimes UPF/PGW-U won't run in a container but a baremetal server for better throughput.
![image](https://user-images.githubusercontent.com/84237986/118367753-b38cad00-b5d3-11eb-9d1e-731f2b36a3aa.png)

**Comment by herlesupreeth** [comment]
P-CSCF does not work with any kind of NAT in the case of IMS registration. You can run UPF/PGW-U and P-CSCF is two separate machines (running on bare machine not containers), the only criteria to make this setup work is to have two machines in the same subnet, no NATing of UE subnet for IMS APN and have a static route from P-CSCF to UPF/PGW-U for the UE subnet corresponding to IMS APN.

**Comment by bluehat-f** [comment]
Thanks for herlesupreeth's quick reply. I understand your suggestion. 
I haven't checked 3gpp specs. What's the limitation for P-CSCF to support IPSEC NAT? 3GPP specs won't consider this kind of issue? Sorry for so many questions.

**Comment by herlesupreeth** [comment]
You are right about 3GPP not imposing such restrictions, its just due to the current implementation of IMS in kamailio restricting usage of NAT.

The reason i say it doesnt work with NAT is that, while in IMS registration the SIP packet source IP gets changed by SNAT and as a result of that P-CSCF uses the source IP to send AAR Rx message with frame-IP-address set to source IP of received packet resulting in failure at PGW-U/UPF since the NATed IP is not part of IMS APN subnet. Lets say we solve this, then there is another issue where IPSec tunnels are created between UE IP and P-CSCF IP, however the packets are no NATed as result of this IPSec SA and Policies doesnt match resulting in dropping of IPSec packets by P-CSCF. Also there are other complications with Address of Record contacts created in P-CSCF (havent completely analyzed them)
