### ISSUE TITLE
SMS Inquiry

### ISSUE THREAD

**Issue by justinmarkr** [herlesupreeth/docker_open5gs#99]
Hi herlesupreeth,

I have question regarding SMS over SGs. I was able to send and received a SMS (9999 to 9998) but unable to send from 9998 to 9999. I've attached the pcap trace. thank you!

[sms.pcap.zip](https://github.com/herlesupreeth/docker_open5gs/files/9348332/sms.pcap.zip)

**Comment by herlesupreeth** [comment]
![image](https://user-images.githubusercontent.com/4115839/185053663-390343a4-898b-493c-b24d-a12657cff29e.png)

I dont think sending SMS 9999 to 9998 and 9998 to 9999 (both ways) worked. Both failed.

SMS over IMS was attempted rather than SMS over SGs. Its completely upto UE to decide which path it chooses

**Comment by justinmarkr** [comment]
Thanks @herlesupreeth

I will try another UE and check the behaviour.
